#!/sbin/openrc-run
# See the git history of this file for the old (shell-script) version.

description="Kernel UEvents to D-Bus system daemon proxy"

depend() {
	need dsme hildon-desktop
}

start_pre() {
	ebegin "Starting hulda ($description)"
	/usr/sbin/waitdbus system
	. /tmp/session_bus_address.user
	/usr/sbin/waitdbus session
}

start() {
	/usr/sbin/dsmetool -U root -n -1 -t /usr/sbin/hulda
}

stop() {
	eend "Stopping hulda ($description)"
	/usr/sbin/dsmetool -k /usr/sbin/hulda
}
